import * as React from 'react';
import Head from 'next/head';
import Navbar from '@/components/Navbar';
import NavbarAuth from '@/components/NavbarAuth';
import { useState, useEffect } from 'react';

export default function App({ Component, pageProps }) {
  const [authorized, setAuthorized] = useState(false);

  React.useEffect(() => {
    authCheck();
  })

  function authCheck(){
    const status = localStorage.getItem('status');
    if (status != 'active') {
      setAuthorized(false);
    } else {
      setAuthorized(true);
    }
  }
  return (
    <>
      <Head>
          <title>E-Commerce</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/icon.png" />
          {/* eslint-disable-next-line @next/next/no-css-tags */}
          <link href="//netdna.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
      </Head>
      <div>
      {authorized ? <NavbarAuth /> : <Navbar/>}
        <Component {...pageProps} />
      </div>
    </>
  )
}
